### ISSUE TITLE
Installation error: config not found

### ISSUE THREAD

**Issue by jakubkazimierczak** [jakubkazimierczak/yt_keeper#1]
# How to reproduce
1. Install as described in README
2. Run

# What's the error?
```
/home/pi/.local/pipx/venvs/yt-keeper/lib/python3.7/site-packages
Traceback (most recent call last):
  File "/home/pi/.local/bin/yt_keeper", line 5, in <module>
    from yt_keeper.__main__ import main
  File "/home/pi/.local/pipx/venvs/yt-keeper/lib/python3.7/site-packages/yt_keeper/__init__.py", line 7, in <module>
    CONFIG = config.load()
  File "/home/pi/.local/pipx/venvs/yt-keeper/lib/python3.7/site-packages/yt_keeper/config.py", line 27, in load
    with open(f'{RELATIVE_ROOT}/config.yml') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.local/pipx/venvs/yt-keeper/lib/python3.7/site-packages/config.yml'
```

**Comment by jakubkazimierczak** [comment]
Fixed in 607102b.
